# Generated by Django 3.2.8 on 2021-11-03 04:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('ctime', models.DateTimeField(default=datetime.datetime(2021, 11, 3, 13, 32, 3, 770865))),
                ('voter', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('pic', models.ImageField(upload_to='vote/%y')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.topic')),
                ('voter', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
