# Generated by Django 3.2.8 on 2021-11-04 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 12, 9, 54, 256434)),
        ),
    ]
