# Generated by Django 3.2.8 on 2021-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_topic_ctime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='top',
            new_name='sub',
        ),
        migrations.AlterField(
            model_name='topic',
            name='ctime',
            field=models.DateTimeField(),
        ),
    ]
