# Generated by Django 3.2.8 on 2021-10-29 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 12, 44, 58, 88197)),
        ),
        migrations.AddField(
            model_name='book',
            name='site_url',
            field=models.TextField(default=0),
        ),
    ]
