# Generated by Django 3.2.8 on 2021-11-04 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 12, 9, 54, 252409)),
        ),
    ]
