# Generated by Django 3.2.8 on 2021-11-05 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 12, 10, 16, 781048)),
        ),
    ]
